# Project info
site_name: j-Wave
site_author: Antonio Stanziola, Biomedical Ultrasound Group
site_description: >-
  Fast and differentiable acoustic simulations in JAX
site_url: https://ucl-bug.github.io/jwave/

# Github info
repo_name: ucl-bug/jwave
repo_url: https://github.com/ucl-bug/jwave

theme:
  name: "material"

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/images/jwave_logo.png

nav:
  - Home: index.md
  - Install:
    - Linux: install/on_linux.md
    - Windows: install/on_win.md
  - API:
    - acoustics:
      - conversion: api_conversion.md
      - operators: api_operators.md
      - time_harmonic: api_time_harmonic.md
      - time_varying: api_time_varying.md
    - extras: api_extras.md
    - geometry: api_geometry.md
    - phantoms: api_phantoms.md
    - signal_processing: api_signal_processing.md
    - utils: api_utils.md
  - Tutorials:
    - Prerequisites: notebooks/prerequisites.ipynb
    - Initial value problems:
      - Homogeneous wave propagation: notebooks/ivp/homogeneous_medium.ipynb
      - 3D simulations: notebooks/ivp/3d.ipynb
      - Sensors: notebooks/ivp/homogeneous_medium_sensors.ipynb
      - Off-Grid Sensors: notebooks/ivp/off_grid_sensors.ipynb
      - Custom sensors: notebooks/ivp/custom_sensors.ipynb
      - Automatic differentiation: notebooks/ivp/homogeneous_medium_backprop.ipynb
      - Heterogeneous medium: notebooks/ivp/heterogeneous_medium.ipynb
    - Time varying:
      - Point sources: notebooks/time_varying/point_sources.ipynb
      - Full wave inversion: notebooks/time_varying/FWI.ipynb
    - Time harmonic:
      - Helmholtz problem: notebooks/harmonic/helmholtz_problem.ipynb
      - Automatic differentiation: notebooks/harmonic/helmholtz_solver_differentiable.ipynb
    - Others:
      - Save video: notebooks/others/save_video.ipynb
      - Uncertainty propagation: notebooks/others/uncertainty_propagation.ipynb
  - Benchmarks:
    - Accuracy: test_reports/test_report.md
  - Changelog: changelog.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ucl-bug/jwave
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/jwave/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UCL_Ultrasound
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VtUb4fFznt

plugins:
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
  - search
  - mermaid2
  - macros:
      module_name: docs/macros

markdown_extensions:
  - toc:
      toc_depth: 5
  - pymdownx.highlight
  - pymdownx.snippets
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details      # For collapsible admonitions
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

use_directory_urls: false

# For mkdocstrings
watch:
  - jwave
