# Project info
site_name: j-Wave
site_author: Antonio Stanziola, Biomedical Ultrasound Group
site_description: >-
  Fast and differentiable acoustic simulations in JAX
site_url: https://ucl-bug.github.io/jwave/

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.annotate
  palette:
    primary: blue gray
  logo: assets/images/jwave_logo.png

nav:
  - Home: index.md
  - Install:
    - Linux: install/on_linux.md
    - Windows: install/on_win.md
  - API:
    - acoustics:
      - conversion: api_conversion.md
      - operators: api_operators.md
      - time_harmonic: api_time_harmonic.md
      - time_varying: api_time_varying.md
    - extras: api_extras.md
    - geometry: api_geometry.md
    - phantoms: api_phantoms.md
    - signal_processing: api_signal_processing.md
    - utils: api_utils.md
  - Tutorials:
    - Prerequisites: notebooks/prerequisites.ipynb
    - Initial value problems:
      - Homogeneous wave propagation: notebooks/ivp/homogeneous_medium.ipynb
      - 3D simulations: notebooks/ivp/3d.ipynb
      - Sensors: notebooks/ivp/homogeneous_medium_sensors.ipynb
      - Custom sensors: notebooks/ivp/custom_sensors.ipynb
      - Automatic differentiation: notebooks/ivp/homogeneous_medium_backprop.ipynb
      - Heterogeneous medium: notebooks/ivp/heterogeneous_medium.ipynb
    - Time varying:
      - Point sources: notebooks/time_varying/point_sources.ipynb
      - Full wave inversion: notebooks/time_varying/FWI.ipynb
    - Time harmonic:
      - Helmholtz problem: notebooks/harmonic/helmholtz_problem.ipynb
      - Automatic differentiation: notebooks/harmonic/helmholtz_solver_differentiable.ipynb
    - Others:
      - Save video: notebooks/others/save_video.ipynb
      - Uncertainty propagation: notebooks/others/uncertainty_propagation.ipynb
  - Benchmarks:
    - Accuracy: test_reports/test_report.md
  - Changelog: changelog.md

plugins:
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
  - search
  - mermaid2
  - macros:
      module_name: docs/macros

markdown_extensions:
  - toc:
      toc_depth: 5
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
  - pymdownx.highlight
  - pymdownx.snippets
  - admonition
  - attr_list
  - footnotes

extra_css:
  - stylesheets/extra.css

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

use_directory_urls: false

# For mkdocstrings
watch:
  - jwave
