name: Build Docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '**.md'
      - '**.ipynb'
      - '**.sh'
      - '**.css'
      - '**.js'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Build docs
        run: uv run mkdocs build
