name: Update Documentation

on:
  release:
    types: [ published ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/python-poetry-env
    - name: Building docs
      run: |
        mkdocs build
    - name: Build documentation
      run: mkdocs gh-deploy --force
