name: Release

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
