name: Unit and Integration Tests

on:
  pull_request:
    paths:
      - '**.py'
      - '**.m'
      - '**.yaml'
      - '**Makefile'

jobs:
  unit_and_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Downloading test data
        run: |
          make get_test_data
      - name: Running tests
        run: |
          uv run coverage run --source=jwave -m pytest -xvs --ignore=tests/regression_tests
          uv run coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: codecov-umbrella
